# Generated by Django 2.2.12 on 2020-07-19 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ichoose', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seller_verification_process',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id_verification_process', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratings_comments',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id_ratings_comments', to='ichoose.buyers'),
        ),
        migrations.AddField(
            model_name='ratings_comments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id_ratings_comments', to='ichoose.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id_product', to='ichoose.sellers'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id_order', to='ichoose.buyers'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_id_order', to='ichoose.product'),
        ),
        migrations.AddField(
            model_name='loan',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_id_loan', to='ichoose.order'),
        ),
        migrations.AddField(
            model_name='loan',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id_loan', to='ichoose.sellers'),
        ),
        migrations.AddField(
            model_name='customization',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id_customization', to='ichoose.buyers'),
        ),
        migrations.AddField(
            model_name='customization',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id_customization', to='ichoose.product'),
        ),
        migrations.AddField(
            model_name='buyers',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
